In [1]:
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]

In [4]:
import numpy as np
import time
size=10000000
py_list=list(range(size))
start=time.time()
sq_list=[x**2 for x in  py_list]
end=time.time()
print(f"python list time taken is{end-start}")
np_array=np.array(py_list)
start=time.time()
sq_arr=np_array**2
end=time.time()
print(f"array list time taken is {end-start}")

python list time taken is2.194126844406128
array list time taken is 0.0668489933013916

In [6]:
import sys
print(f"python list size={sys.getsizeof(py_list)*len(py_list)}")
print(f" numpy array size={np_array.nbytes}")

python list size=800000560000000
 numpy array size=80000000

In [7]:
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr,type(arr),arr.shape)

[1 2 3 4 5] <class 'numpy.ndarray'> (5,)

In [8]:
arr2=np.array([1,2,3,4,5,"prime"])
print(arr2,type(arr2),arr2.shape)

['1' '2' '3' '4' '5' 'prime'] <class 'numpy.ndarray'> (6,)

In [11]:
arr2d=np.array([[1,2],[4,5],[7,8]])
print(arr2d,type(arr2d),arr2d.shape)

[[1 2]
 [4 5]
 [7 8]] <class 'numpy.ndarray'> (3, 2)

In [12]:
arr1=np.zeros((2,3),dtype="int64")
print(arr1,arr1.shape)

[[0 0 0]
 [0 0 0]] (2, 3)

In [15]:
arr2=np.ones((5,2))
print(arr2,type(arr2),arr2.shape)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]] <class 'numpy.ndarray'> (5, 2)

In [16]:
arr3=np.full((3,4),100)
print(arr3,arr3.shape)

[[100 100 100 100]
 [100 100 100 100]
 [100 100 100 100]] (3, 4)

In [18]:
arr4=np.eye(3,4)
print(arr4,arr4.shape)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]] (3, 4)

In [19]:
arr5=np.arange(1,11)
print(arr5)

[ 1  2  3  4  5  6  7  8  9 10]

In [20]:
arr6=np.linspace(1,100,3)
print(arr6)

[  1.   50.5 100. ]

In [31]:
arr=np.array([1,2,3,4,5])
idx=[0,1,3]
print(arr[idx])

[1 2 4]

In [32]:
arr=np.array([1,2,3,4,5])
print(arr[arr>1])
print(arr[arr%2==0])
print(arr[arr%2!=0])

[2 3 4 5]
[2 4]
[1 3 5]

In [34]:
arr=np.array([1,2,3,4,5])
print(arr[1:4])
print(arr[1:])

[2 3 4]
[2 3 4 5]

In [36]:
nums=[1,2,3,4,5]
sub_list=nums[1:3]
print(sub_list)
sub_list[0]="sonu"
print(sub_list)

[2, 3]
['sonu', 3]

In [45]:
#2d array
arr2d=np.array([[1,2,3],[4,5,6],[7,8,9]])
sum_of_col=np.sum(arr2d,axis=0)
print(sum_of_col)
sum_of_row=np.sum(arr2d,axis=1)
print(sum_of_row)
print(arr2d[0:2,1:2])

[12 15 18]
[ 6 15 24]
[[2]
 [5]]

In [58]:
arr1=np.array([1,1,1,1,1])
arr2=np.array([[1,2,3,4,5],[1,2,3,4,5]])
print(arr1+arr2)

[[2 3 4 5 6]
 [2 3 4 5 6]]

In [62]:
arr=np.array([[1,2],[3,4]])
mean=np.mean(arr)
std=np.std(arr)
norm_arr=(arr-mean)/std
print(norm_arr)

[[-1.34164079 -0.4472136 ]
 [ 0.4472136   1.34164079]]

In [65]:
arr=np.array([1,2,3,4,5])
print(np.square(arr))
print(np.sqrt(arr))
print(np.pow(arr,4))

[ 1  4  9 16 25]
[1.         1.41421356 1.73205081 2.         2.23606798]
[  1  16  81 256 625]

In [67]:
arr=np.array([1,2,3,4,5])
print(np.log(arr))
print(np.log2(arr))
print(np.exp(arr))

[0.         0.69314718 1.09861229 1.38629436 1.60943791]
[0.         1.         1.5849625  2.         2.32192809]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]

In [9]:
import pandas as pd
info={"Name":["mohan","harshitha","shradha"],
"age":[22,23,24]}
data=pd.DataFrame(info)
data

        Name  age
0      mohan   22
1  harshitha   23
2    shradha   24

In [12]:
import pandas as pd 
s=pd.Series([1,2,3,4,5])
print(s)

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [16]:
s=pd.Series(([1,2,3]),index=["adam","bob","charlie"])
print(s)

adam       1
bob        2
charlie    3
dtype: int64

In [18]:
s1=pd.Series([1,2,3,4])
s2=pd.Series([1,1,1,1])
s1[0]=100
changed=s1.drop(0)
print(s1)
print(changed)

0    100
1      2
2      3
3      4
dtype: int64
1    2
2    3
3    4
dtype: int64

In [23]:
info={
    "NAME":["bob","charlie","adam"],
    "age":[22,23,24],
    "gpa":[9.5,9.2,9.6]
}
data=pd.DataFrame(info)
print(data.columns)

Index(['NAME', 'age', 'gpa'], dtype='object')

In [26]:
df=pd.DataFrame([["adam",23],["bob",24],["charlie",26]],columns=["name","age"])
df

      name  age
0     adam   23
1      bob   24
2  charlie   26

In [27]:
import numpy as np
import pandas as pd
np_arr=np.array([[1,2,3],[4,5,6]])
df=pd.DataFrame(np_arr,columns=["a","b","c"])
print(df)

   a  b  c
0  1  2  3
1  4  5  6

In [28]:
import pandas as pd
df=pd.read_csv("employee_data.csv")
df

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000
5   6    Frank   29    Finance   50000
6   7    Grace   41         HR   82000
7   8   Hannah   26  Marketing   47000
8   9      Ian   35         IT   75000
9  10    Julia   30    Finance   60000

In [29]:
df.head()

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000

In [30]:
df.tail()

   ID    Name  Age Department  Salary
5   6   Frank   29    Finance   50000
6   7   Grace   41         HR   82000
7   8  Hannah   26  Marketing   47000
8   9     Ian   35         IT   75000
9  10   Julia   30    Finance   60000

In [31]:
df.sample()

   ID Name  Age Department  Salary
8   9  Ian   35         IT   75000

In [32]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   ID          10 non-null     int64
 1   Name        10 non-null     object
 2   Age         10 non-null     int64
 3   Department  10 non-null     object
 4   Salary      10 non-null     int64
dtypes: int64(3), object(2)
memory usage: 532.0+ bytes

In [35]:
d=df.shape
print(d)

(10, 5)

In [3]:
import pandas as pd
df=pd.read_csv("raw_data.csv")
df

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [30]:
age_mean=df["age"].mean()
cleaned_data=df.copy()
age_mean=cleaned_data["age"].mean()
cleaned_data["age"]=cleaned_data["age"].fillna(age_mean)
cleaned_data

    id          name    age country   gender   income
0    1      John Doe  29.00     USA     Male  55000.0
1    1      John Doe  29.00     USA     Male  55000.0
2    2    Jane Smith  32.75  Canada   Female  62000.0
3    3          Alex  32.75     USA  Unknown  47000.0
4    4  Maria Garcia  34.00   Spain   Female      NaN
5    5        Li Wei  27.00   China     Male  51000.0
6    6           NaN  45.00   India   Female  73000.0
7    7    Ahmed Khan  38.00     NaN     Male  68000.0
8    8    Rachel Lee  29.00     USA   Female  62000.0
9    9   Carlos Ruiz  32.75  Mexico     Male  45000.0
10  10   Emily Davis  31.00     USA      NaN  58000.0

In [37]:
df.dtypes
df2=df.copy()
df2=df.fillna(0)
df2=df2["age"].astype("int32").copy()
df2

0     29
1     29
2      0
3      0
4     34
5     27
6     45
7     38
8     29
9      0
10    31
Name: age, dtype: int32

In [47]:
df=pd.read_csv("raw_data.csv")
df["country"].str.contains("us")

0         [John, Doe]
1         [John, Doe]
2       [Jane, Smith]
3              [Alex]
4     [Maria, Garcia]
5           [Li, Wei]
6                 NaN
7       [Ahmed, Khan]
8       [Rachel, Lee]
9      [Carlos, Ruiz]
10     [Emily, Davis]
Name: name, dtype: object

In [61]:
df2=df.copy()
df2["country"]=df2["country"].replace("USA","us")
df2

    id          name   age country   gender   income
0    1      John Doe  29.0      us     Male  55000.0
1    1      John Doe  29.0      us     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN      us  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0      us   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0      us      NaN  58000.0

In [52]:
df2=df.copy()
gender_map={"Male":"M","Female":"F","Unknown":"u"}
df2=df2["gender"].map(gender_map)
df2

0       M
1       M
2       F
3       u
4       F
5       M
6       F
7       M
8       F
9       M
10    NaN
Name: gender, dtype: object

In [68]:
df2=df.copy()
df2.columns=["id","name","age","country","tax","new_income"]
df2=df2.rename(columns={"country":"s"})
df2

    id          name   age       s      tax  new_income
0    1      John Doe  29.0     USA     Male     55000.0
1    1      John Doe  29.0     USA     Male     55000.0
2    2    Jane Smith   NaN  Canada   Female     62000.0
3    3          Alex   NaN     USA  Unknown     47000.0
4    4  Maria Garcia  34.0   Spain   Female         NaN
5    5        Li Wei  27.0   China     Male     51000.0
6    6           NaN  45.0   India   Female     73000.0
7    7    Ahmed Khan  38.0     NaN     Male     68000.0
8    8    Rachel Lee  29.0     USA   Female     62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male     45000.0
10  10   Emily Davis  31.0     USA      NaN     58000.0

In [69]:
df2=df.copy()
df2.rename(index={1:"first"})

       id          name   age country   gender   income
0       1      John Doe  29.0     USA     Male  55000.0
first   1      John Doe  29.0     USA     Male  55000.0
2       2    Jane Smith   NaN  Canada   Female  62000.0
3       3          Alex   NaN     USA  Unknown  47000.0
4       4  Maria Garcia  34.0   Spain   Female      NaN
5       5        Li Wei  27.0   China     Male  51000.0
6       6           NaN  45.0   India   Female  73000.0
7       7    Ahmed Khan  38.0     NaN     Male  68000.0
8       8    Rachel Lee  29.0     USA   Female  62000.0
9       9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10     10   Emily Davis  31.0     USA      NaN  58000.0

In [93]:
df=pd.read_csv("raw_data.csv")
df=df.groupby("country").agg({
    "income":"mean",
    "age":"mean"})
df

          income   age
country
Canada   62000.0   NaN
China    51000.0  27.0
India    73000.0  45.0
Mexico   45000.0   NaN
Spain        NaN  34.0
USA      55400.0  29.5

In [99]:
import pandas as pd
df=pd.DataFrame({
    "country":["usa","usa","india","india"],
    "year":[2020,2021,2020,2021],
    "sales":[100,120,90,110],
    "profit":[20,15,18,22]
})
melted_df=df.melt(
    id_vars=["country","year"],
    value_vars=["sales","profit"],
    var_name="metrics",
    value_name="value")
original=melted_df.pivot(
    index=["country","year"],
    columns="metrics",
    values="value")
original

metrics       profit  sales
country year
india   2020      18     90
        2021      22    110
usa     2020      20    100
        2021      15    120

In [104]:
df_customers=pd.DataFrame({
    "customer_id":[1,2,3,4],
    "name":["adam","bob","charlie","dave"]
})
df_orders=pd.DataFrame({
    "order_id":[101,102,104,105],
    "customer_id":[2,1,4,5],
    "amount":[250,120,130,180]})
pd.merge(df_customers,df_orders,on="customer_id")

   customer_id  name  order_id  amount
0            1  adam       102     120
1            2   bob       101     250
2            4  dave       104     130

In [106]:
df1=pd.DataFrame({
    "id":[1,2,3],
    "name":["adma","bob","charlie"]
})
df2=pd.DataFrame({
    "id":[4,5,6],
    "name":["luck","foster","baarbee"]})
pd.concat([df1,df2])

   id     name
0   1     adma
1   2      bob
2   3  charlie
0   4     luck
1   5   foster
2   6  baarbee

In [7]:
import requests
url="https://stephen-king-api.onrender.com/api/books"
res=requests.get(url)
json_data=res.json()
import pandas as pd
df=pd.json_normalize(json_data["data"])
df=df[["id","Title","Year"]]
df

    id          Title  Year
0    1         Carrie  1974
1    2    Salem's Lot  1975
2    3    The Shining  1977
3    4           Rage  1977
4    5      The Stand  1978
..  ..            ...   ...
58  59   The Outsider  2018
59  60      Elevation  2018
60  61  The Institute  2019
61  62          Later  2021
62  63  Billy Summers  2021

[63 rows x 3 columns]

In [13]:
import requests
url="https://www.scrapethissite.com/pages/simple"
res=requests.get(url)
print(res.headers)

{'Date': 'Sun, 18 Jan 2026 12:36:54 GMT', 'Content-Type': 'text/html; charset=utf-8', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Nel': '{"report_to":"heroku-nel","response_headers":["Via"],"max_age":3600,"success_fraction":0.01,"failure_fraction":0.1}', 'Report-To': '{"group":"heroku-nel","endpoints":[{"url":"https://nel.heroku.com/reports?s=otkIBPwCT3tjr77n39%2BvK767EB8QCxSRS%2FWdG8I5ZbA%3D\\u0026sid=67ff5de4-ad2b-4112-9289-cf96be89efed\\u0026ts=1768739813"}],"max_age":3600}', 'Reporting-Endpoints': 'heroku-nel="https://nel.heroku.com/reports?s=otkIBPwCT3tjr77n39%2BvK767EB8QCxSRS%2FWdG8I5ZbA%3D&sid=67ff5de4-ad2b-4112-9289-cf96be89efed&ts=1768739813"', 'Server': 'cloudflare', 'Via': '1.1 heroku-router', 'cf-cache-status': 'DYNAMIC', 'Content-Encoding': 'zstd', 'CF-RAY': '9bfe23faba2c182b-MAA', 'alt-svc': 'h3=":443"; ma=86400'}

In [43]:
from bs4 import BeautifulSoup
with open("scraped_data/data.html","r") as f:
    html_content=f.read()
soup=BeautifulSoup(html_content,"html.parser")
all_h3=soup.find_all("h3")
all_countries=[]
for h3 in all_h3:
    name=h3.get_text(strip=True)
    population=(h3.find_next("div").select_one("span.country-population").get_text(strip=True))
    all_countries.append([name,population])
import pandas as pd
df=pd.DataFrame(all_countries,columns=(["name","population"]))
df

                     name population
0                 Andorra      84000
1    United Arab Emirates    4975593
2             Afghanistan   29121286
3     Antigua and Barbuda      86754
4                Anguilla      13254
..                    ...        ...
245                 Yemen   23495361
246               Mayotte     159042
247          South Africa   49000000
248                Zambia   13460305
249              Zimbabwe   11651858

[250 rows x 2 columns]